---
- hosts: controlplane
  remote_user: ubuntu
  become: yes


  roles:
    - controlplane


- hosts: workernode
  remote_user: ubuntu
  become: yes


  roles:
    - workernode


- name: Get kubeadm join command from master
  hosts: controlplane
  become: true
  tasks:

    - name: Create token and get join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Save join command in a fact
      set_fact:
        kubeadm_join_command: "{{ join_command.stdout }}"
      # Save this fact globally, so it is accessible to all hosts
      delegate_facts: true

- name: Join Kubernetes Worker Nodes
  hosts: workernode
  become: yes
  tasks:
    - name: Use the join command to join the cluster
      shell: "{{ hostvars['controlplane']['kubeadm_join_command'] }}"
      args:
        executable: /bin/bash

