---
- hosts: controlplane
  remote_user: ubuntu
  become: yes


  roles:
    - controlplane


- hosts: workernode
  remote_user: ubuntu
  become: yes


  roles:
    - workernode


- hosts: all
  remote_user: ubuntu
  become: yes


  roles:
    - joinworkernode

