---
- hosts: controlplane
  remote_user: ubuntu
  become: yes


  roles:
    - controlplane


- hosts: workernode
  remote_user: ubuntu
  become: yes


  roles:
    - workernode


- hosts: controlplane
  remote_user: ubuntu
  become: yes


  roles:
    - joinworkernode


- hosts: controlplane
  remote_user: ubuntu
  become: yes


  roles:
    - Install-ingress-nginx
