- name: Create token and get join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Save join command in a fact
  set_fact:
    kubeadm_join_command: "{{ join_command.stdout }}"
  # Save this fact globally, so it is accessible to all hosts
    delegate_facts: true
    cacheable: yes


- name: Use the join command to join the cluster
  ansible.builtin.shell: "{{ kubeadm_join_command }}"
  args:
    executable: /bin/bash
  delegate_to: "{{ item }}"
  with_items:
    - 13.49.46.174
